[KALMAN_PARAM]
AREA="ALL_AREA_HALF_HALF_POOL3" # フィルタリング対象のエリア（下で定義されたエリアのうちどれかを設定）
#PATH_SAVE="E:/shunsukeE//result//removed_badship_ais_changedFillterInAIS" # 保存先
PATH_SAVE="E:/shunsukeE//result//original_ais_minLambda0-0_halfhalfArea-retry" # 保存先
Q_VALUES=[0.1, 0.01] # JCOPEの分散値
N_D=2000 # 使用するデータの最大数（Dを昇順に並べ替えたときの上位N_Dを使用）(未使用パラメータ)
N_LAMBDA=2000 # 使用するデータの最大数（固有値を昇順に並べ替えたときの上位N_lambda個を使用）(未使用パラメータ)
MIN_D=10000 # 使用するDの下限(未使用パラメータ)
MIN_LAMBDA1=0 # 使用する固有値(小)の下限
MIN_LAMBDA2=0 # 使用する固有値(大)の下限
USE_SHIPVAR=false # 各船の海流の誤差を考慮して海流の計算をするか？
USE_AIS_MEDIAN=false # 偏流値の計算に交点の中央を採用した結果を使用するか？
USE_AIS_REMOVE_BAD_MMSI=false # 偏流の計算に値の悪いMMSIを取り除いた結果を使用するか？

[ANALYSIS_PARAM]
PATH_LOG="E:/shunsukeE//result//original_ais_minLambda10-100_halfhalfArea-Q0.1" # 読み込むログのフォルダ(-Q0.1など忘れずに！)
#PATH_LOG="E:/shunsukeE//result//removed_brokenship_ais_minLambda0-0_halfhalfArea-retry-Q0.1" # 読み込むログのフォルダ(-Q0.1など忘れずに！)
PATH_SHIP="E:/shunsukeE//data//shiplog" # 船のログのフォルダ
MAX_DAY=29 #1-29 or 30 最大日数（月末日の場合-1する, 9月は29で最大日数）
MAX_HOUR=24 #1-24 最大時間数
DAY=0 #使ってない値
HOUR=0 #使ってない値 
USE_PICKLE=true
AIS_JCOPE_TEST=false#true # ais, jcopeと船の違いを分析
VISUALIZE=false # カルマンフィルタのログの可視化
EVALUATION=true #false# カルマンフィルタ, ais, jcopeの違いを分析

[TEST_MODE]
POOL_SIZE=3
KUROSIO_LAT_RANGE1=[30.0, 32.0] # x00 x01
KUROSIO_LAT_RANGE2=[30.0, 34.0] # x10 x11
KUROSIO_LON_RANGE=[131.0, 136.0] # y0 y1
PATH_AIS="E:/shunsukeE/data/ais/1509-ais4s-pkls-pooled3" # AISデータの保存先
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先

[TEST_MODE2]
POOL_SIZE=1
KUROSIO_LAT_RANGE1=[20.0, 28.0] # x00 x01
KUROSIO_LAT_RANGE2=[27.0, 36.0] # x10 x11
KUROSIO_LON_RANGE=[120.0, 142.0] # y0 y1
PATH_AIS="" # AISデータの保存先
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先


[WEST_AREA]
POOL_SIZE=2
KUROSIO_LAT_RANGE1=[26.0, 32.0] # x00 x01
KUROSIO_LAT_RANGE2=[30.0, 34.0] # x10 x11
KUROSIO_LON_RANGE=[131.0, 136.0] # y0 y1
PATH_AIS="E:/shunsukeE/data/ais/1509-ais4s-pkls-pooled2"
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先


[EAST_AREA]
POOL_SIZE=2
KUROSIO_LAT_RANGE1=[30, 32] # x00 x01
KUROSIO_LAT_RANGE2=[34, 36] # x10 x11
KUROSIO_LON_RANGE=[136.0, 142.0]
PATH_AIS=""
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先


# pool size 6はaisがnanでつぶれるためおすすめしない (nan以外で平均取るように修正済みだから問題ない？)
[ALL_AREA_POOL6]
POOL_SIZE=6
KUROSIO_LAT_RANGE1=[20.0, 28.0] # x00 x01
KUROSIO_LAT_RANGE2=[27.0, 36.0] # x10 x11
KUROSIO_LON_RANGE=[120.0, 142.0] # y0 y1
PATH_AIS="E:/shunsukeE/data/ais/1509-ais4s-pkls-pooled6-entire"
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先

# 現在おすすめのテスト環境
[ALL_AREA_POOL3]
POOL_SIZE=3
KUROSIO_LAT_RANGE1=[20.0, 28.0] # x00 x01
KUROSIO_LAT_RANGE2=[27.0, 36.0] # x10 x11
KUROSIO_LON_RANGE=[120.0, 142.0] # y0 y1
PATH_AIS="E:/shunsukeE/data/ais/1509-ais4s-pkls-pooled3-entire-around"
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先

[ALL_AREA2]
POOL_SIZE=3
KUROSIO_LAT_RANGE1=[20.0, 28.0] # x00 x01
KUROSIO_LAT_RANGE2=[27.0, 36.0] # x10 x11
KUROSIO_LON_RANGE=[120.0, 142.0] # y0 y1
PATH_AIS="E:/shunsukeE/data/ais/1509-ais4s-pkls-pooled3-entire-around"
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先

# メモリ的に実行不可能
[ALL_AREA]
POOL_SIZE=1
KUROSIO_LAT_RANGE1=[20.0, 28.0] # x00 x01
KUROSIO_LAT_RANGE2=[27.0, 36.0] # x10 x11
KUROSIO_LON_RANGE=[120.0, 142.0] # y0 y1
PATH_AIS=""
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先

# 九州-千葉の黒潮
[ALL_AREA_HALF_POOL3]
POOL_SIZE=3
KUROSIO_LAT_RANGE1=[23.6, 32.2] # x00 x01
KUROSIO_LAT_RANGE2=[27.0, 36.0] # x10 x11
KUROSIO_LON_RANGE=[131.5, 142.0] # y0 y1
PATH_AIS="E:/shunsukeE/data/ais/1509-ais4s-pkls-pooled3-entire-around"
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先

# 九州-千葉の黒潮 上半分
[ALL_AREA_HALF_HALF_POOL3]
POOL_SIZE=3
KUROSIO_LAT_RANGE1=[27.9, 32.2] # x00 x01
KUROSIO_LAT_RANGE2=[31.5, 36.0] # x10 x11
KUROSIO_LON_RANGE=[131.5, 142.0] # y0 y1
PATH_AIS="E:/shunsukeE/data/ais/1509-ais4s-pkls-pooled3-entire-around"
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先

[DEFAULT_AREA]
POOL_SIZE=1
KUROSIO_LAT_RANGE1=[20-1/36, 50+1/36]
KUROSIO_LAT_RANGE2=
KUROSIO_LON_RANGE=[117-1/36, 150+1/36]
