[KALMAN_PARAM]
AREA="ALL_AREA" # フィルタリング対象のエリア（下で定義されたエリアのうちどれかを設定）
PATH_SAVE="E:/shunsukeE//result//ais_removed_bad_mmsi" # 保存先
Q_VALUES=[0.1, 0.01] # JCOPEの分散値
N_D=2000 # 使用するデータの最大数（Dを昇順に並べ替えたときの上位N_Dを使用）
N_LAMBDA=2000 # 使用するデータの最大数（固有値を昇順に並べ替えたときの上位N_lambda個を使用）
MIN_D=10000 # 使用するDの下限
MIN_LAMBDA=10 # 使用する固有値の下限
USE_SHIPVAR=false # 各船の海流の誤差を考慮して海流の計算をするか？
USE_AIS_MEDIAN=false # 偏流値の計算に交点の中央を採用した結果を使用するか？
USE_AIS_REMOVE_BAD_MMSI=true # 偏流の計算に値の悪いMMSIを取り除いた結果を使用するか？

[ANALYSIS_PARAM]
PATH_LOG="E:/shunsukeE//result//ais_removed_bad_mmsi0.1" # 読み込むログのフォルダ
PATH_SHIP="E:/shunsukeE//data//shiplog" # 船のログのフォルダ
MAX_DAY=3 #1-30 or 31 29or30? 最大日数
MAX_HOUR=24 #1-24 最大時間数
DAY=1 #1- 使わない値 
HOUR=6 #1-24 使わない値 

[TEST_MODE]
POOL_SIZE=3
KUROSIO_LAT_RANGE1=[30.0, 32.0] # x00 x01
KUROSIO_LAT_RANGE2=[30.0, 34.0] # x10 x11
KUROSIO_LON_RANGE=[131.0, 136.0] # y0 y1
PATH_AIS="E:/shunsukeE/data/ais/1509-ais4s-pkls-pooled3" # AISデータの保存先
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先

[TEST_MODE2]
POOL_SIZE=1
KUROSIO_LAT_RANGE1=[20.0, 28.0] # x00 x01
KUROSIO_LAT_RANGE2=[27.0, 36.0] # x10 x11
KUROSIO_LON_RANGE=[120.0, 142.0] # y0 y1
PATH_AIS="" # AISデータの保存先
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先


[WEST_AREA]
POOL_SIZE=2
KUROSIO_LAT_RANGE1=[26.0, 32.0] # x00 x01
KUROSIO_LAT_RANGE2=[30.0, 34.0] # x10 x11
KUROSIO_LON_RANGE=[131.0, 136.0] # y0 y1
PATH_AIS="E:/shunsukeE/data/ais/1509-ais4s-pkls-pooled2"
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先


[EAST_AREA]
POOL_SIZE=2
KUROSIO_LAT_RANGE1=[30, 32] # x00 x01
KUROSIO_LAT_RANGE2=[34, 36] # x10 x11
KUROSIO_LON_RANGE=[136.0, 142.0]
PATH_AIS=""
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先


# pool size 6はaisがnanでつぶれるためおすすめしない
[ALL_AREA]
POOL_SIZE=6
KUROSIO_LAT_RANGE1=[20.0, 28.0] # x00 x01
KUROSIO_LAT_RANGE2=[27.0, 36.0] # x10 x11
KUROSIO_LON_RANGE=[120.0, 142.0] # y0 y1
PATH_AIS="E:/shunsukeE/data/ais/1509-ais4s-pkls-pooled6-entire"
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先


[ALL_AREA2]
POOL_SIZE=3
KUROSIO_LAT_RANGE1=[20.0, 28.0] # x00 x01
KUROSIO_LAT_RANGE2=[27.0, 36.0] # x10 x11
KUROSIO_LON_RANGE=[120.0, 142.0] # y0 y1
PATH_AIS="E:/shunsukeE/data/ais/1509-ais4s-pkls-pooled3-entire-around"
PATH_JCOPE="E:/shunsukeE//data//eas2" # jcopeデータの保存先
