FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu20.04 as base
LABEL maintainer="Shunsuke Ueki"
RUN apt update
RUN apt-get -y install \
    clang \
    curl \
    git \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    sudo
RUN mkdir project 
WORKDIR /project

RUN sudo pip3 install --upgrade pip
RUN sudo pip3 install matplotlib

# install
COPY . .
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN pip3 install --upgrade setuptools testresources
RUN pip3 install --upgrade -r requirements.txt
RUN pip3 install --upgrade cmake

# minimal image for development in Python
FROM python:3.6-slim-buster as python-slim
RUN mkdir project
WORKDIR /project
COPY --from=base /project .
RUN pip3 install --upgrade -r requirements.txt
#ENV PYTHONPATH=${PYTHONPATH}:/project